### ISSUE TITLE
Improve the README

### ISSUE THREAD

**Issue by Dharmik48** [Dharmik48/todo-list-app#1]
We need to add install steps, screenshots, etc., and properly organize the README

**Comment by neelakantan-ca** [comment]
Hi, I'm new to github and would like to contribute

I would like to take this on, however I don't know the installation steps.

Is the installation simply cloning the repo and opening the html file in browser ?

**Comment by Dharmik48** [comment]
Hey @Cantej, thank you for showing your interest in contributing!

As for installation steps, you can refer [this](https://github.com/Dharmik48/meme-generator/blob/main/README.md) (one of my other project's README). You can just replace the links and screenshots to this repos links and screenshots.

**Comment by neelakantan-ca** [comment]
Hey just letting you know #13

**Comment by Dharmik48** [comment]
Closed with #13
