### ISSUE TITLE
Added task can be empty

### ISSUE THREAD

**Issue by salocor** [Dharmik48/todo-list-app#10]
A task can be added without text. This should be an easy fix.

**Comment by Dharmik48** [comment]
How do you plan to fix this? If a user enters an empty task, how will you tell them that it can't be empty?

**Comment by salocor** [comment]
A message could appear over the textbox informing them that the textbox cannot be empty

**Comment by Dharmik48** [comment]
Alright, sounds good. But try to keep it consistent with the theme.
