### ISSUE TITLE
Screenshots in readme are too big

### ISSUE THREAD

**Issue by salocor** [Dharmik48/todo-list-app#14]
I noticed the screenshots in the readme are kind of big. They could be cropped to show some of the background (25px?) but not the entire page. Also, rounded corners on the screenshots are always cool.

**Comment by Dharmik48** [comment]
Yeah, your points are valid. And the screenshot right now does not have any tasks, so we can add some tasks and then take the screenshot!

I am assigning this to you.

**Comment by salocor** [comment]
Alright. I won't be available for the next couple of days so it may take me longer than usual but I'll get it done when I can.

**Comment by Dharmik48** [comment]
Yeah, no problem
