### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by Dharmik48** [Dharmik48/todo-list-app#17]
We want to add issue templates to [this repo](https://github.com/Dharmik48/notes-react-firebase-v2.0/tree/master/.github/ISSUE_TEMPLATE) similar to this repo

**Comment by rsk2** [comment]
Hey @Dharmik48, I would like to contribute to this project. If I understand correctly, for this issue we need to create the required folders and issue templates in this repository just like the ones in [this repository](https://github.com/Dharmik48/notes-react-firebase-v2.0/tree/master/.github/ISSUE_TEMPLATE), is that correct?

**Comment by Dharmik48** [comment]
> Hey @Dharmik48, I would like to contribute to this project. If I understand correctly, for this issue we need to create the required folders and issue templates in this repository just like the ones in [this repository](https://github.com/Dharmik48/notes-react-firebase-v2.0/tree/master/.github/ISSUE_TEMPLATE), is that correct?

Yes, correct! I will assign you for this issue😊
