### ISSUE TITLE
[DOCS] Change of the word "useless" 

### ISSUE THREAD

**Issue by glopzel** [Dharmik48/todo-list-app#19]
### Description

There's an error in the first lines of the README where it refers to the app as "useless". It could be changed to "useful" or "practical". 

### Screenshots

![git-issue-docs](https://user-images.githubusercontent.com/74939915/185815956-b75f350e-761e-4e2a-a0f6-8248491ea4c2.jpg)

**Comment by Dharmik48** [comment]
Oops! That's a huge typo! Thanks a lot for noticing!

Why don't you raise a PR fixing it?
