### ISSUE TITLE
todos are not saved

### ISSUE THREAD

**Issue by Dharmik48** [Dharmik48/todo-list-app#2]
Currently, the todos are not saved in a database or local storage. 

So we need to save them to local storage.

**Comment by lukeecart** [comment]
Hi @Dharmik48 I saw this on twitter and I've created a PR to add the items to local storage :D 
Please see https://github.com/Dharmik48/todo-list-app/pull/3

**Comment by Dharmik48** [comment]
Hey @lukeecart, Thanks a lot for the contribution 😄

Your code is great! But I found one issue where if I have completed a todo and checked it then if I refresh the page, it becomes unchecked.

If want to solve it then you can create a [new issue](https://github.com/Dharmik48/todo-list-app/issues/new) for it and I will assign it to you.

**Comment by lukeecart** [comment]
Thank you. I saw this and thought I'd give it a go. 

That might require a bit more changes. I'll save each task as an object. 

You can check the local storage by going to the application tab on chrome dev tools

**Comment by Dharmik48** [comment]
I think it's a good idea to save the tasks as ab object so we can have a `{task: 'something', completed: true}`.

You can give it a try🚀

**Comment by Dharmik48** [comment]
Closed with #8
