### ISSUE TITLE
hover  for cancel 

### ISSUE THREAD

**Issue by JayrajSingh65** [Dharmik48/todo-list-app#21]
### Hey,
- #### Jayraj is here I just want to add that can we add hover for  cancel button for the background colour to red.
- #### I want to work on this issue can you assign this to me waiting ......

**Comment by Dharmik48** [comment]
Hey @JayrajSingh65, thanks for raising the issue.

We can surely add a hover effect to the cancel button but the red color won't go with the theme of the app.

So I think we can use the purple color from the theme

What do you think?

**Comment by JayrajSingh65** [comment]
> Hey @JayrajSingh65, thanks for raising the issue.
> 
> We can surely add a hover effect to the cancel button but the red color won't go with the theme of the app.
> 
> So I think we can use the purple color from the theme
> 
> What do you think?

- I am working on this issue, can you assign me this also helpful for hactober fest 2022.

- I will consider the theme, but I think light red will be good so that it can't disturb the theme  and make a good user experience for cancel button

**Comment by JayrajSingh65** [comment]
> > Hey @JayrajSingh65, thanks for raising the issue.
> > 
> > We can surely add a hover effect to the cancel button but the red color won't go with the theme of the app.
> > 
> > So I think we can use the purple color from the theme
> > 
> > What do you think?
> 
> - I am working on this issue, can you assign me this also helpful for hactober fest 2022.
> 
> - I will consider the theme, but I think light red will be good so that it can't disturb the theme  and make a good user experience for cancel button 

-  or should we use themes colours? What do you think 🤔

**Comment by Dharmik48** [comment]
I viewed your PR and those changes look great! Soni've merged it

**Comment by JayrajSingh65** [comment]
> I viewed your PR and those changes look great! Soni've merged it

Thanks
