### ISSUE TITLE
[FEATURE] When the add-task section is visible, user should also be able to click on the blurred area to make it hidden again

### ISSUE THREAD

**Issue by deeppomal** [Dharmik48/todo-list-app#22]
### Description

This type of feature is available in all kinds of the dialog box and modal libraries in react native. I have noticed this typical user pattern where the user clicks on the blurred background to make the Add Note dialog go away. Currently, only clicking on the cancel button will make it go away.

I have already coded the basic idea, if you think this feature will be helpful let me know I will submit the PR.

**Comment by Dharmik48** [comment]
This is an absolutely necessary feature! It is true that almost all users tend to click outside the dialog box to close it (including me). So it will be a great addition!

**Comment by deeppomal** [comment]
I have submitted a PR for this issue, please have a look and let me know
