### ISSUE TITLE
Completed tasks dont stay completed 

### ISSUE THREAD

**Issue by lukeecart** [Dharmik48/todo-list-app#4]
Since the PR was merged to save the tasks to local storage the tasks are saved but not their state(completed or not)

The local storage will need to be refreshed to store the tasks as objects.

e.g.[ {title: 'task 1', completed: true} ]

**Comment by Dharmik48** [comment]
Yeah, you can store every task as an object so the checked one stay checked even after refreshing the page.

**Comment by lukeecart** [comment]
@Dharmik48 There is also a security bug to html / js injection.

Inserting `<img src='abc' />`  as a task displays an image... and cannot be deleted unless local storage is cleared

**Comment by Dharmik48** [comment]
I think its because we are setting the new todo with the `innerHTML` method so it inserts it as actual `img` tag

**Comment by lukeecart** [comment]
Yep, exactly. We'd need to change the logic to creating the element then setting the innerText to the input.

I've raised a separate Issue for that

**Comment by Dharmik48** [comment]
Yes, I saw your issue. Are you willing to work on that?

**Comment by lukeecart** [comment]
@Dharmik48 Can we close this issue now its been closed by #8

**Comment by Dharmik48** [comment]
Yeah, I forgot to close this😅

**Comment by Dharmik48** [comment]
Closed with #8
