### ISSUE TITLE
New task window scales with current tasks window size

### ISSUE THREAD

**Issue by salocor** [Dharmik48/todo-list-app#6]
The new task window gets taller as you add more tasks. This can create visual issues as more tasks are added. This can be fixed by making the new task window static. Even better would be a window that starts at a certain size but can grow as text is added. <br>
<img width="614" alt="Screen Shot 2022-07-31 at 10 22 27 PM" src="https://user-images.githubusercontent.com/58708222/182077774-d8a96abb-3ce7-4a32-a620-025993cc5e6d.png">
<img width="614" alt="Screen Shot 2022-07-31 at 10 22 23 PM" src="https://user-images.githubusercontent.com/58708222/182077768-cc6ba8cb-3536-48be-bf6d-aa06627c082c.png">
<img width="614" alt="Screen Shot 2022-07-31 at 10 22 11 PM" src="https://user-images.githubusercontent.com/58708222/182077754-f6527793-1ae2-4c1f-8a1e-d5debeed89b0.png">
<img width="614" alt="Screen Shot 2022-07-31 at 10 22 15 PM" src="https://user-images.githubusercontent.com/58708222/182077764-f11764ab-71d4-4149-b2a4-2c367a7cd648.png">

**Comment by Dharmik48** [comment]
Your point is valid, it can create a very bad user experience if there are a lot of tasks!

Would you like to work on this?

**Comment by salocor** [comment]
Sure. I'll get right to work.
